name: RacesAndClasses
main: de.tobiyas.racesandclasses.RacesAndClasses
version: 1.0.5
website: http://dev.bukkit.org/bukkit-mods/racesandclasses/
author: tobiyas
loadbefore: [Vault]
description: >
             Races and Classes for Players